# Generated by Django 5.2.4 on 2025-07-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='communes',
            field=models.ManyToManyField(blank=True, related_name='delivery_zones', to='geolocation.guineacommune'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='prefectures',
            field=models.ManyToManyField(blank=True, related_name='delivery_zones', to='geolocation.guineaprefecture'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='delivery_zones', to='geolocation.guinearegion'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationverification',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
