# Generated by Django 5.2.4 on 2025-07-22 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_alter_deliveryzone_communes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='communes',
            field=models.ManyToManyField(blank=True, related_name='delivery_zones', to='geolocation.guineacommune', verbose_name='Communes'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='prefectures',
            field=models.ManyToManyField(blank=True, related_name='delivery_zones', to='geolocation.guineaprefecture', verbose_name='Préfectures'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='delivery_zones', to='geolocation.guinearegion', verbose_name='Régions'),
        ),
        migrations.AlterField(
            model_name='guineacommune',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='guineacommune',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='geolocation.guineaprefecture', verbose_name='Préfecture'),
        ),
        migrations.AlterField(
            model_name='guineaprefecture',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='guineaprefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefectures', to='geolocation.guinearegion', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='guinearegion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.guineacommune', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.guineaprefecture', verbose_name='Préfecture'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.guinearegion', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='verification_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de vérifications'),
        ),
        migrations.AlterField(
            model_name='locationverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='locationverification',
            name='location_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='geolocation.locationpoint', verbose_name='Point de localisation'),
        ),
        migrations.AlterField(
            model_name='locationverification',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to='geolocation.locationpoint', verbose_name='Point de localisation'),
        ),
    ]
