# Generated by Django 5.2.4 on 2025-07-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_alter_deliveryzone_communes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpoint',
            old_name='created_by',
            new_name='user',
        ),
    ]
