# Generated by Django 5.2.4 on 2025-07-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_rename_created_by_locationpoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpoint',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal'),
        ),
    ]
