# Generated by Django 5.2.4 on 2025-07-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('processing', 'En cours de traitement'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('defective', 'Produit défectueux'), ('wrong_item', 'Mauvais article'), ('not_as_described', 'Non conforme à la description'), ('damaged', 'Endommagé pendant le transport'), ('changed_mind', "Changement d'avis"), ('size_issue', 'Problème de taille'), ('quality_issue', 'Problème de qualité'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de retour',
                'verbose_name_plural': 'Demandes de retour',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.TextField(verbose_name='État du produit')),
                ('images', models.JSONField(default=list, verbose_name='Photos du produit')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
            options={
                'verbose_name': 'Article de retour',
                'verbose_name_plural': 'Articles de retour',
            },
        ),
        migrations.CreateModel(
            name='ReturnShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pickup_address', models.TextField(verbose_name='Adresse de récupération')),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='returns.returnrequest')),
            ],
            options={
                'verbose_name': 'Expédition de retour',
                'verbose_name_plural': 'Expéditions de retour',
            },
        ),
    ]
