# Generated by Django 5.2.4 on 2025-07-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('geolocation', '0002_alter_deliveryzone_communes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_zones', to='geolocation.deliveryzone')),
                ('seller', models.ForeignKey(limit_choices_to={'user_type': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zone de livraison du vendeur',
                'verbose_name_plural': 'Zones de livraison des vendeurs',
                'unique_together': {('seller', 'delivery_zone')},
            },
        ),
    ]
