# Generated by Django 5.2.4 on 2025-07-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Commande passée'), ('order_confirmed', 'Commande confirmée'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('order_cancelled', 'Commande annulée'), ('payment_received', 'Paiement reçu'), ('product_low_stock', 'Stock faible'), ('new_review', 'Nouvel avis'), ('delivery_request', 'Demande de livraison'), ('delivery_accepted', 'Livraison acceptée'), ('promotion', 'Promotion'), ('system', 'Système')], max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('url', models.URLField(blank=True, verbose_name='Lien')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
