# Generated by Django 5.2.4 on 2025-07-19 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_delivery_zone_delivery_location_point'),
        ('geolocation', '0002_alter_deliveryzone_communes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='paid_by',
            field=models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur')], default='buyer', max_length=20, verbose_name='Payé par'),
        ),
        migrations.AlterField(
            model_name='deliveryrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('availability_status', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible')], default='available', max_length=20, verbose_name='Statut de disponibilité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('location_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_persons', to='geolocation.locationpoint', verbose_name='Position actuelle')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
            },
        ),
    ]
