# Generated by Django 5.2.4 on 2025-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_paid_by_alter_deliveryrating_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'Vélo'), ('car', 'Voiture'), ('van', 'Camionnette'), ('other', 'Autre')], max_length=20, verbose_name='Type de véhicule'),
        ),
    ]
